sudo: false
language: python
python:
  - 2.7
install:
  - nvm install 4.4.7
  - pip install -r requirements.txt
  - npm install grunt-cli -g
  - npm install
script:
  - npm run build
  - npm run lint
  - nosetests
